version: '3.4'

services:
  lock-generator:
    build:
      context: .
      target: pdm
      dockerfile: Dockerfile-pdm
      args:
        - GITHUB_USER
        - GITHUB_PIP_TOKEN
    environment:
      GITHUB_PIP_TOKEN:
    working_dir: /code
    volumes:
      - ../..:/code