default_language_version:
  python: python3.9

default_stages:
  - commit

exclude: |
  (?x)^(
      .circleci/.*|
      .platform/.*|
      __pypackages__/.*|
      .*/dbt_packages/.*|
      .*/target/.*
  )$

repos:
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
      - id: black
        name: black-lint
        args:
          - "--check"
          - "--diff"
          - "--color"
        stages: [manual]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args:
          - "--show-source"
          - "--fix"
          - "--no-update-check"
          - "--force-exclude"
          - "--format"
          - "grouped"
      - id: ruff
        name: ruff-lint
        args:
          - "--show-source"
          - "--no-fix"
          - "--no-update-check"
          - "--force-exclude"
          - "--format"
          - "grouped"
        stages: [manual]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        stages:
          - commit
      - id: trailing-whitespace
        stages:
          - commit

  - repo: https://github.com/pdm-project/pdm
    rev: 2.11.1
    hooks:
      - id: pdm-lock-check

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        name: yaml-lint
        stages:
          - commit
          - manual

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks-docker
