[project]
name = "dagster_template"
dynamic = ["version"]
description = ""
authors = [
    {name = "nextail"},
]
dependencies = [
    "dagster>=1.1.5",
    "dagit>=1.1.5",
    "dagster-graphql>=1.1.5",
    "dagster-cloud>=1.1.5",
    "dagster-postgres",
    "dagster-aws",
    "dagster-docker",
    "dagster-dbt",
    "dagster-k8s",
]
requires-python = ">=3.9"
license = {text = "MIT"}


[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.1.2",
]
debug = [
    "debugpy==1.6.3",
]