[project]
name = "dagster_template"
dynamic = ["version"]
description = ""
license = { text = "Nextail private use" }
authors = [
    {name = "nextail"},
]
dependencies = [
    "dagster==1.6.3",
    "dagster-cloud==1.6.3",
    "dagster-aws==0.22.3",
    "dagster-docker==0.22.3",
    "dagster-dbt==0.22.3",
    "dagster-k8s==0.22.3",
    "dagster-snowflake==0.22.3"
]
requires-python = ">=3.9, <3.10"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.3.1",
]
dev = [
    "dagster-webserver==1.6.3",
    "dagster-postgres==0.22.3",
    "debugpy==1.8.0",
    # linter and formatter
    "pre-commit==3.6.0",
    "black==24.1.1",                   # python formatter
    "ruff==v0.1.13",                  # python linter (flake8 compatible)
    "yamllint==1.33.0",                # yaml linter
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra --ignore-glob=__pypackages__/**"

[tool.pyright]
pythonVersion = "3.9"
exclude = ["**/__pycache__", "**/__pypackages__"]
ignore = ["**/__pypackages__"]
reportGeneralTypeIssues = false                                      # to allow working with dagster resources retrieved from context

[tool.black]
line-length = 120
target-version = ["py39"]
preview = true

[tool.isort]
profile = "black"
py_version = "39"
line_length = 120

[tool.ruff]
extend-exclude = ["__pypackages__"]
line-length = 120
target-version = "py39"
select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "Q",   # flake8-quotes
    "N",   # pep8-naming
    "E",   # Pycodestyle
    "W",   # Pycodestyle
    "F",   # Pyflakes
    "I",   # isort
    "RUF", # Ruff-specific rules
]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
