config-version: 2

name: nextail
version: "0.0.1"
require-dbt-version: ">=1.9.2"

profile: nx_internal_profile

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # "dbt_date:time_zone": "America/Los_Angeles"
  "dbt_date:time_zone": "Etc/UTC"
  "tenant": "nextail"

flags:
  send_anonymous_usage_stats: false
  use_colors: true
  # partial_parse: <true | false>
  # printer_width: <integer>
  # write_json: <true | false>
  # warn_error: <true | false>
  # warn_error_options: <include: all | include: [<error-name>] | include: all, exclude: [<error-name>]>
  # log_format: <text | json | default>
  debug: false
  # version_check: <true | false>
  # fail_fast: <true | false>
  # use_experimental_parser: <true | false>
  # static_parser: <true | false>

models:
  +materialized: table
  +transient: true
  +persist_docs:
    relation: true
    column: true

  nextail:
    staging:
      +schema: nx_bronze

    silver:
      +schema: nx_silver

    dt_silver:
      +schema: nx_silver_dt

    gold:
      +schema: nx_gold
      
# dispatch:
#   - macro_namespace: dbt
#     search_order:
#       - nx_internal_reporting
#       - dbt_snowflake_query_tags
#       - dbt
