version: 2.1

# cumtom orb for dagster pipelines
orbs:
  dagster-pipelines-orb: nextail/dagster-pipelines-orb@2.1.0

parameters:
  custom_service_account:
    type: boolean
    default: false
    description: "We use this parameter to define if our project uses its own service account (true) or by default (false)."
  module_name:
    type: string
    default: dagster_template.dagster
    description: "Python module containing the target Dagster Definitions"

workflows:
  infrastructure:
    jobs:

      # internal tool to deploy our Helm chart
      - dagster-pipelines-orb/service-account-sandbox:
          context:
            - org-global
          filters:
            branches:
              only:
                - sandbox

      # internal tool to deploy our Helm chart
      - dagster-pipelines-orb/service-account-production:
          context:
            - org-global
          filters:
            branches:
              only:
                - main

  build-and-deploy:
    jobs:

      # check secrets on code
      - dagster-pipelines-orb/check-secrets

      ## pre-commit for all branches
      - dagster-pipelines-orb/pre-commit

      # unit-test for all branches
      - dagster-pipelines-orb/tests:
          context:
            - github-tokens

      # build-and-deploy for sandbox dagster environment
      - dagster-pipelines-orb/build-and-deploy-sandbox:
          custom_service_account: <<pipeline.parameters.custom_service_account>>
          module_name: <<pipeline.parameters.module_name>>
          requires:
            - dagster-pipelines-orb/pre-commit
            - dagster-pipelines-orb/check-secrets
            - dagster-pipelines-orb/tests
          context:
            - org-global
            - github-tokens
            - dagster-tokens
          filters:
            branches:
              only:
                - sandbox

      # build-and-deploy for prod dagster environment
      # uncomment to deploy to production
      #
      # - dagster-pipelines-orb/build-and-deploy-production:
      #     custom_service_account: <<pipeline.parameters.custom_service_account>>
      #     module_name: <<pipeline.parameters.module_name>>
      #     requires:
      #       - dagster-pipelines-orb/pre-commit
      #       - dagster-pipelines-orb/check-secrets
      #       - dagster-pipelines-orb/tests
      #     context:
      #       - org-global
      #       - github-tokens
      #       - dagster-tokens
      #     filters:
      #       branches:
      #         only:
      #           - main
