version: 2.1

# custom orb for dagster pipelines
orbs:
  dagster-pipelines-orb: nextail/dagster-pipelines-orb@3.3.2

parameters:
  custom_service_account:
    type: boolean
    default: false
    description: "Define if our project uses its own service account (true) or by default (false)."
  module_name:
    type: string
    default: dagster_template.dagster
    description: "Python module containing the target Dagster Definitions"
  project_name:
    type: string
    default: default
    description: "By default all projects will be named as {github-repo-name}-default"
  branch_deployment:
    type: string
    default: /deploy\/.*/
    description: "Regex for branch deployments. For example: deploy/**"
  code_location_resource_limit_memory:
    type: string
    description: Kubernetes Limits - the container can never consume more than the CPU amount indicated.
    default: 256Mi
  job_run_resource_limit_cpu:
    type: string
    description: Kubernetes Limits - the container can never consume more than the memory amount indicated.
    default: 500m
  job_run_resource_limit_memory:
    type: string
    description: Kubernetes Limits - the container can never consume more than the CPU amount indicated.
    default: 1Gi
  GHA_Actor:
    type: string
    description: Integration with Github Actions
    default: ""
  GHA_Action:
    type: string
    description: Integration with Github Actions
    default: ""
  GHA_Event:
    type: string
    description: Integration with Github Actions
    default: ""
  GHA_Meta:
    type: string
    description: Integration with Github Actions
    default: ""

workflows:
  # This workflow is set to be conditionally triggered, only when
  # the GitHub Action is triggered .
  external-trigger-open:
    when:
      and:
        - equal: [OPEN, << pipeline.parameters.GHA_Meta >>]
    jobs:
      # check secrets on code
      - dagster-pipelines-orb/check-secrets

      # run make test
      - dagster-pipelines-orb/tests:
          context:
            - github-tokens

      # build-and-deploy for branch deployment environment
      - dagster-pipelines-orb/build-and-deploy-branch:
          actor_op: <<pipeline.parameters.GHA_Actor>>
          trigger_op: <<pipeline.parameters.GHA_Meta>>
          custom_service_account: <<pipeline.parameters.custom_service_account>>
          module_name: <<pipeline.parameters.module_name>>
          project_name: <<pipeline.parameters.project_name>>
          code_location_resource_limit_memory: <<pipeline.parameters.code_location_resource_limit_memory>>
          job_run_resource_limit_cpu: <<pipeline.parameters.job_run_resource_limit_cpu>>
          job_run_resource_limit_memory: <<pipeline.parameters.job_run_resource_limit_memory>>
          requires:
            - dagster-pipelines-orb/check-secrets
            - dagster-pipelines-orb/tests
          context:
            - org-global
            - github-tokens
            - dagster-tokens
  # This workflow is set to be conditionally triggered, only when
  # the GitHub Action is triggered.
  external-trigger-close-or-merge:
    when:
      or:
        - equal: [CLOSED, <<pipeline.parameters.GHA_Meta>>]
        - matches: {pattern: <<pipeline.parameters.branch_deployment>>, value: <<pipeline.parameters.GHA_Meta>>}
    jobs:
      # build-and-deploy for branch deployment environment
      - dagster-pipelines-orb/build-and-deploy-branch:
          actor_op: <<pipeline.parameters.GHA_Actor>>
          trigger_op: <<pipeline.parameters.GHA_Meta>>
          custom_service_account: <<pipeline.parameters.custom_service_account>>
          module_name: <<pipeline.parameters.module_name>>
          project_name: <<pipeline.parameters.project_name>>
          code_location_resource_limit_memory: <<pipeline.parameters.code_location_resource_limit_memory>>
          job_run_resource_limit_cpu: <<pipeline.parameters.job_run_resource_limit_cpu>>
          job_run_resource_limit_memory: <<pipeline.parameters.job_run_resource_limit_memory>>
          context:
            - org-global
            - github-tokens
            - dagster-tokens

  infrastructure:
    when:
      and:
        - not: <<pipeline.parameters.GHA_Action>>
    jobs:
      # internal tool to deploy our Helm chart
      - dagster-pipelines-orb/service-account-sandbox:
          context:
            - org-global
          filters:
            branches:
              only:
                - sandbox

      # internal tool to deploy our Helm chart
      - dagster-pipelines-orb/service-account-production:
          context:
            - org-global
          filters:
            branches:
              only:
                - main

  build-and-deploy:
    when:
      and:
        - not: <<pipeline.parameters.GHA_Action>>
    jobs:
      # check secrets on code
      - dagster-pipelines-orb/check-secrets:
          filters:
            branches:
              ignore:
                - <<pipeline.parameters.branch_deployment>>

      # pre-commit
      - dagster-pipelines-orb/pre-commit:
          python-executor: dagster-pipelines-orb/py3-11-executor
          filters:
            branches:
              ignore:
                - sandbox
                - <<pipeline.parameters.branch_deployment>>

      # run make test
      - dagster-pipelines-orb/tests:
          context:
            - github-tokens
          filters:
            branches:
              ignore:
                - <<pipeline.parameters.branch_deployment>>

      # build-and-deploy for sandbox dagster environment
      - dagster-pipelines-orb/build-and-deploy-sandbox:
          custom_service_account: <<pipeline.parameters.custom_service_account>>
          module_name: <<pipeline.parameters.module_name>>
          project_name: <<pipeline.parameters.project_name>>
          code_location_resource_limit_memory: <<pipeline.parameters.code_location_resource_limit_memory>>
          job_run_resource_limit_cpu: <<pipeline.parameters.job_run_resource_limit_cpu>>
          job_run_resource_limit_memory: <<pipeline.parameters.job_run_resource_limit_memory>>
          requires:
            - dagster-pipelines-orb/check-secrets
            - dagster-pipelines-orb/tests
          context:
            - org-global
            - github-tokens
            - dagster-tokens
          filters:
            branches:
              only:
                - sandbox

      # build-and-deploy for prod dagster environment
      # uncomment to deploy to production
      # - dagster-pipelines-orb/build-and-deploy-production:
      #     custom_service_account: <<pipeline.parameters.custom_service_account>>
      #     module_name: <<pipeline.parameters.module_name>>
      #     project_name: <<pipeline.parameters.project_name>>
      #     code_location_resource_limit_memory: <<pipeline.parameters.code_location_resource_limit_memory>>
      #     job_run_resource_limit_cpu: <<pipeline.parameters.job_run_resource_limit_cpu>>
      #     job_run_resource_limit_memory: <<pipeline.parameters.job_run_resource_limit_memory>>
      #     requires:
      #       - dagster-pipelines-orb/pre-commit
      #       - dagster-pipelines-orb/check-secrets
      #       - dagster-pipelines-orb/tests
      #     context:
      #       - org-global
      #       - github-tokens
      #       - dagster-tokens
      #     filters:
      #       branches:
      #         only:
      #           - main
