scheduler:
  module: dagster._core.scheduler
  class: DagsterDaemonScheduler
  config: {}

run_coordinator:
  module: dagster._core.run_coordinator
  class: DefaultRunCoordinator
  config: {}

run_launcher:
  module: dagster
  class: DefaultRunLauncher
  config: {}

run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      hostname: 
        env: POSTGRES_HOST
      username:
        env: POSTGRES_USER
      password:
        env: POSTGRES_PASSWORD
      db_name:
        env: POSTGRES_DB
      port: 5432

schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      hostname: 
        env: POSTGRES_HOST
      username:
        env: POSTGRES_USER
      password:
        env: POSTGRES_PASSWORD
      db_name:
        env: POSTGRES_DB
      port: 5432

# Configures how long Dagster waits for repositories
# to load before timing out.
code_servers:
  local_startup_timeout: 900

telemetry:
  enabled: false