version: "3.9"

services:

  # This service runs the postgres DB used by dagster for run storage, schedule storage,
  # and event log storage.
  postgres_db:
    image: postgres:11
    container_name: ${SERVICE_NAME}_postgres
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    networks:
      - nxnet

  # This service runs dagit, which loads your user code from the user code container.
  # Since our instance uses the QueuedRunCoordinator, any runs submitted from dagit will be put on
  # a queue and later dequeued and launched by dagster-daemon.
  dagit:
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      target: srv
      args:
        - GITHUB_PIP_TOKEN #This can be removed if is not planned to use Nextail libraries.
    working_dir: /usr/src/dagster
    image: nextail/${SERVICE_NAME}_dagit
    container_name: ${SERVICE_NAME}_dagit
    restart: on-failure
    entrypoint:
      - "python"
      - "-m"
      - "debugpy"
      - "--listen"
      - "0.0.0.0:5678"
      - "-m"
      - "dagit"
      - "-h"
      - "0.0.0.0"
      - "-p"
      - "3000"
      - "-w"
      - "workspace.yaml"
    environment:
      POSTGRES_HOST: ${SERVICE_NAME}_postgres
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "3000:3000"
      - "5678:5678"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../dagster:/usr/src/dagster
      - ../../dagster/dagster.yaml:/opt/dagster/dagster.yaml
    depends_on:
      - postgres_db
    networks:
      - nxnet

  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  daemon:
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      target: srv
      args:
        - GITHUB_PIP_TOKEN #This can be removed if is not planned to use Nextail libraries.
    working_dir: /usr/src/dagster
    image: nextail/${SERVICE_NAME}_daemon
    container_name: ${SERVICE_NAME}_daemon
    restart: on-failure
    entrypoint:
      - "python"
      - "-m"
      - "debugpy"
      - "--listen"
      - "0.0.0.0:5678"
      - "-m"
      - "dagster._daemon"
      - "run"
    environment:
      POSTGRES_HOST: ${SERVICE_NAME}_postgres
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5679:5678"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../dagster:/usr/src/dagster
      - ../../dagster/dagster.yaml:/opt/dagster/dagster.yaml
    depends_on:
      - postgres_db
    networks:
      - nxnet

networks:
  nxnet:
    driver: bridge
    name: nxnet