load_from:
  - python_module:
      location_name: nx-dbt-default
      module_name: nx_dbt.dagster
      working_directory: /opt/nx-dbt/

  # - dbt_project:
  #     location_name: dbt_project
  #     module_name: dbt_project
  #     working_directory: /opt/dbt_project/
