config-version: 2

name: nextail
version: "0.0.1"
require-dbt-version: ">=1.9.2"

profile: nx_internal_profile

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "DBT_WAREHOUSE": "{{ env_var('DBT_WAREHOUSE') }}"  # required to set the config in the dynamic tables;
  # we need to set a dbt var because the config block cannot use env_var
  "full_refresh_start_date": "2025-01-01"
  "dbt_date:time_zone": "Etc/UTC"
  "tenant": "nextail"
  # to be modified to include the centralized configuration of tenants
  "all_tenants": [
    "ARISTOCRAZY",
    # "BASE",
    "BIMANI",
    "BZB",
    "CALLIOPE",
    "DCK",
    "DUB",
    "ECIBOLSOSMMEE",
    "ECICAMISERIACABALLEROMMEE",
    "ECIEASYWEARELLA",
    "ECIGAP",
    "ECIKIDS",
    "ECILLOYDSMEN",
    "ECIZAPATERIASENORAS",
    "ECRU",
    "ETHNICITY",
    "FLYINGTIGER",
    "FOOTGEAR",
    "FOREVERNEW",
    "GINATRICOT",
    "GSTARRETAIL",
    "GSTAR",
    "GUESSEMEA",
    "GUESSUS",
    "HACKETT",
    "JOTT",
    "JULES",
    "MAAG",
    "MERKAL",
    "METROBRANDS",
    "MFG",
    "MOUNTAINWAREHOUSE",
    "PEPE",
    "RIVERISLAND",
    "SCOTTA",
    "SILBON",
    "SFERABASICMAN",
    # "SISIFO",
    "SPORTSEMOTION",
    "SPORTSTREET",
    "SUAREZ",
    "TERRANOVA",
    "TVOE",
    "VALEXTRA",
    "VILET",
    "WHITESTUFF",
    "WOOLRICH"
  ]

flags:
  send_anonymous_usage_stats: false
  use_colors: true
  # partial_parse: <true | false>
  # printer_width: <integer>
  # write_json: <true | false>
  # warn_error: <true | false>
  # warn_error_options: <include: all | include: [<error-name>] | include: all, exclude: [<error-name>]>
  # log_format: <text | json | default>
  debug: false
  # version_check: <true | false>
  # fail_fast: <true | false>
  # use_experimental_parser: <true | false>
  # static_parser: <true | false>

models:
  +materialized: table
  +transient: true
  +persist_docs:
    relation: true
    # column: true
  +grants:
    select:
      # we want to use BI_READER_PROD_RL for production and BI_READER_SANDBOX_RL for sandbox, but the
      # NX_ENVIRONMENT envvar is either PRODUCTION or SANDBOX.
      # The following code resolves this
      - "BI_READER_{{ 
          'PROD' if env_var('NX_ENVIRONMENT', 'NX_ENVIRONMENT_NOT_SET') | upper == 'PRODUCTION' 
          else 'SANDBOX' if env_var('NX_ENVIRONMENT', 'NX_ENVIRONMENT_NOT_SET') | upper == 'SANDBOX' 
          else 'NX_ENVIRONMENT_NOT_SET' 
        }}_RL"
  nextail:
    # must be NEXTAIL_INTERNALS_<ENVIRONMENT>_DB
    +database: "{{ env_var('DBT_DATABASE') }}"
    costs:
      costs_staging:
        +schema: nx_costs_bronze
      costs_silver:
        +schema: nx_costs_silver
      costs_gold:
        +schema: nx_gold
      # DEPRECATED FOLDERS
      DEPRECATED:
        +enabled: false
    internal:
      internal_staging:
        +schema: nx_internals_bronze
    sales_engineering:
      +schema: nx_sales_engineering_playground
