config-version: 2

name: "nx_internal_reporting"
version: "3.0.0"
require-dbt-version: ">=1.9.0"

# dbt-cloud:
#   project-id: 275557 # Put your project id here

profile: default # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # "dbt_date:time_zone": "America/Los_Angeles"
  "dbt_date:time_zone": "	Etc/UTC"
  "tenant": "nextail"

flags:
  send_anonymous_usage_stats: false
  use_colors: true
  # partial_parse: <true | false>
  # printer_width: <integer>
  # write_json: <true | false>
  # warn_error: <true | false>
  # warn_error_options: <include: all | include: [<error-name>] | include: all, exclude: [<error-name>]>
  # log_format: <text | json | default>
  debug: false
  # version_check: <true | false>
  # fail_fast: <true | false>
  # use_experimental_parser: <true | false>
  # static_parser: <true | false>

models:
  nx_internal_reporting:
    +materialized: table
    # staging:
    #   +materialized: table
    # marts:
    #   +materialized: table

# dispatch:
#  - macro_namespace: dbt
#    search_order:
#      - MY_DBT_PROJECT_NAME
#      - dbt_snowflake_query_tags
#      - dbt

# query-comment:
  # comment: '{{ dbt_snowflake_query_tags.get_query_comment(node) }}'
  # comment: '{{ dbt_snowflake_query_tags.get_query_comment(node, extra={"run_started_at": builtins.run_started_at | string }) }}'
  # append: true # Snowflake removes prefixed comments.