nx_internal_profile:
  target: nx_internal_sandbox
  outputs:
    nx_internal_production:
      type: snowflake
      account: xo52081.eu-west-1
      user: DBT
      private_key: "{{ env_var('DBT_RSA_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_RSA_PASSPHRASE') }}"
      role: DBT_PROD_RL
      database: NEXTAIL_INTERNALS_PROD_DB
      warehouse: DATAPLATFORM_INTERNAL_WH
      schema: DBT
      threads: 8

      # optional
      connect_retries: 0  # default 0
      connect_timeout: 10  # default: 10
      retry_on_database_errors: false  # default: false
      retry_all: false  # default: false
      reuse_connections: true  # default: True if client_session_keep_alive is False, otherwise None

    nx_internal_sandbox:
      type: snowflake
      account: xo52081.eu-west-1
      user: DBT
      private_key: "{{ env_var('DBT_RSA_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_RSA_PASSPHRASE') }}"
      role: DBT_SANDBOX_RL
      database: NEXTAIL_INTERNALS_SANDBOX_DB
      warehouse: DATAPLATFORM_INTERNAL_WH
      schema: DBT
      threads: 8

      # optional
      connect_retries: 0  # default 0
      connect_timeout: 10  # default: 10
      retry_on_database_errors: false  # default: false
      retry_all: false  # default: false
      reuse_connections: true  # default: True if client_session_keep_alive is False, otherwise None
