version: '3.4'

services:
  dev:
    container_name: dev
    build:
      context: ./..
      dockerfile: .devcontainer/Dockerfile
    image: nextail/operations-workspace:dev
    environment:
      GITHUB_TOKEN:
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/..:/opt/dagster-template:cached
    command: sleep infinity
