{{- if .Values.sharedParameters }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Chart.Name }}-params
spec:
  provider: aws
  parameters:
    region: eu-west-1
    objects: |
      {{- range .Values.sharedParameters }}
      - objectName: "/{{ $.Values.environment }}/{{ .Name }}"
        objectType: "ssmparameter"
      {{- if .Alias }}
        objectAlias: "{{ .Alias }}"
      {{- end}}
      {{- end }}
    pathTranslation: "_"
{{- end }}
