{{- if .Values.envFromSecretsManager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Chart.Name }}-secrets
spec:
  provider: aws
  parameters:
    region: eu-west-1
    objects: |
      - objectName: "{{ .Values.environment }}/{{ .Chart.Team }}/dbt"
        objectType: "secretsmanager"
        objectAlias: "secrets"
        jmesPath:
          {{- range .Values.envFromSecretsManager }}
          - path: {{ .key }}
            objectAlias: {{ .key }}
          {{- end }}

  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:
    - secretName: {{ .Chart.Name }}-secret
      type: Opaque
      data:
        {{- range .Values.envFromSecretsManager }}
        - objectName: {{ .key }}
          key: {{ .envVar }}
        {{- end }}
{{- end }}
