{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::989535222017:role/{{ .Values.environment }}-{{ .Chart.Name }}"
{{- end }}
